In [1]:
import numpy as np

In [2]:
sales = [[0, 2, 5, 7, 10], [14.50, 11.50, 11.50, 1.50, 1]]

In [3]:
sales_array = np.array(sales)
sales_array

array([[ 0. ,  2. ,  5. ,  7. , 10. ],
       [14.5, 11.5, 11.5,  1.5,  1. ]])

In [4]:
sales_array * 2

array([[ 0.,  4., 10., 14., 20.],
       [29., 23., 23.,  3.,  2.]])

In [5]:
quiz_scores = np.array([[70, 80, 90], [0, 20, 80]])
quiz_scores

array([[70, 80, 90],
       [ 0, 20, 80]])

In [6]:
quiz_scores.ndim

2

In [7]:
names = np.array(["Tim", "Jane", "Oliver", "Patty"])
names

array(['Tim', 'Jane', 'Oliver', 'Patty'], dtype='<U6')

In [8]:
# array slicing
names[-1]

'Patty'

In [9]:
# array slicing with colon
names[3:]
names[:3]
names[::2]
names[0::3]

array(['Tim', 'Patty'], dtype='<U6')

In [10]:
quiz_scores

array([[70, 80, 90],
       [ 0, 20, 80]])

In [11]:
quiz_scores[0][0]
quiz_scores[0, 0:2]
quiz_scores[:2, 1]

array([80, 20])

In [12]:
sales_array

array([[ 0. ,  2. ,  5. ,  7. , 10. ],
       [14.5, 11.5, 11.5,  1.5,  1. ]])

In [13]:
quantity = sales_array[0]
quantity

array([ 0.,  2.,  5.,  7., 10.])

In [14]:
price = sales_array[1]
price

array([14.5, 11.5, 11.5,  1.5,  1. ])

In [15]:
revenue = quantity * price
revenue

array([ 0. , 23. , 57.5, 10.5, 10. ])

In [16]:
revenue.sum()

101.0

In [17]:
# filtering 
sales_array 

array([[ 0. ,  2. ,  5. ,  7. , 10. ],
       [14.5, 11.5, 11.5,  1.5,  1. ]])

In [18]:
sales_array != 0

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
sales_array[sales_array != 0]

array([ 2. ,  5. ,  7. , 10. , 14.5, 11.5, 11.5,  1.5,  1. ])

In [20]:
sales_array[(sales_array == 10) | (sales_array > 7)]

array([10. , 14.5, 11.5, 11.5])

In [21]:
mask = (sales_array == 10) | (sales_array > 7)

In [22]:
sales_array[mask]

array([10. , 14.5, 11.5, 11.5])

In [23]:
# filter arrays based on other arrays
my_array = np.array([0, 5, 155, 0, 519])
my_array

array([  0,   5, 155,   0, 519])

In [24]:
fruit_array = np.array(['plum', 'kiwi', 'grape', 'mulberry', 'passion fruit'])
fruit_array

array(['plum', 'kiwi', 'grape', 'mulberry', 'passion fruit'], dtype='<U13')

In [25]:
fruit_array[(my_array > 0)]

array(['kiwi', 'grape', 'passion fruit'], dtype='<U13')

In [26]:
fruit_array[0] = 'coconut'
fruit_array

array(['coconut', 'kiwi', 'grape', 'mulberry', 'passion fruit'],
      dtype='<U13')

In [27]:
my_array[my_array == 0] = 5
my_array

array([  5,   5, 155,   5, 519])

In [28]:
# 1. create 2 arrays of your choice 
# 2. perform filtering on those arrays
# 3. perform slicing on those arrays

animals = np.array(['cat', 'dog', 'lion', 'elephant', 'cow'])
code = np.array([3, 5, 1, 6, 9])

In [29]:
animals[(code >= 5)]

array(['dog', 'elephant', 'cow'], dtype='<U8')

In [30]:
animals[(code == 5)] = 'cheeta'
animals

array(['cat', 'cheeta', 'lion', 'elephant', 'cow'], dtype='<U8')

In [31]:
animals[(animals == 'cat') | (animals == 'elephant')]

array(['cat', 'elephant'], dtype='<U8')

In [32]:
code[:3]

array([3, 5, 1])

In [33]:
animals[::2]

array(['cat', 'lion', 'cow'], dtype='<U8')

In [34]:
code[1::3]

array([5, 9])

In [35]:
animals[1::3]

array(['cheeta', 'cow'], dtype='<U8')

In [57]:
#aggregate functions
# where function 
# np.where(condition, value if True, value if false)
inventory_array = np.array([0, 0, 100, 100, 0])
inventory_array

array([  0,   0, 100, 100,   0])

In [58]:
product_array = np.array(['apple', 'pear', 'date', 'fig', 'plum'])
product_array

array(['apple', 'pear', 'date', 'fig', 'plum'], dtype='<U5')

In [59]:
np.where(inventory_array <= 0, "out of stock", "In stock")

array(['out of stock', 'out of stock', 'In stock', 'In stock',
       'out of stock'], dtype='<U12')

In [60]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
np.where(my_array % 2 == 0, "It's even", "It's odd")

array(["It's even", "It's odd", "It's even", "It's odd", "It's even",
       "It's odd", "It's even", "It's odd", "It's even", "It's odd",
       "It's even", "It's odd", "It's even", "It's odd", "It's even",
       "It's odd", "It's even", "It's odd", "It's even", "It's odd"],
      dtype='<U9')

In [62]:
np.where(my_array % 2 == 0, "Even", np.where(my_array == 9, my_array, "odd"))

array(['Even', 'odd', 'Even', 'odd', 'Even', 'odd', 'Even', 'odd', 'Even',
       '9', 'Even', 'odd', 'Even', 'odd', 'Even', 'odd', 'Even', 'odd',
       'Even', 'odd'], dtype='<U11')

In [63]:
sales_array

array([[ 0. ,  2. ,  5. ,  7. , 10. ],
       [14.5, 11.5, 11.5,  1.5,  1. ]])

In [64]:
sales_array.sum()

64.0

In [65]:
sales_array.sum(axis = 0)

array([14.5, 13.5, 16.5,  8.5, 11. ])

In [67]:
sales_array.sum(axis = 1)

array([24., 40.])

In [70]:
sales_array.mean(axis = 0)

array([7.25, 6.75, 8.25, 4.25, 5.5 ])

In [76]:
np.median(sales_array, axis = 1)

array([ 5. , 11.5])

In [77]:
np.unique(sales_array)

array([ 0. ,  1. ,  1.5,  2. ,  5. ,  7. , 10. , 11.5, 14.5])

In [78]:
np.sqrt(sales_array)

array([[0.        , 1.41421356, 2.23606798, 2.64575131, 3.16227766],
       [3.80788655, 3.39116499, 3.39116499, 1.22474487, 1.        ]])

In [79]:
np.sort(sales_array)

array([[ 0. ,  2. ,  5. ,  7. , 10. ],
       [ 1. ,  1.5, 11.5, 11.5, 14.5]])

In [80]:
sales_array

array([[ 0. ,  2. ,  5. ,  7. , 10. ],
       [14.5, 11.5, 11.5,  1.5,  1. ]])

In [81]:
sales_array.max()

14.5

In [82]:
sales_array.min()

0.0

In [83]:
sales_array.argmax()

5

In [84]:
sales_array.argmin()

0

In [85]:
sales_array.std()

4.963869458396343